(function(root){
'use strict';
// Each row is a distinct authored scene. Polish and Russian are stored together.
const rows=`
Powrót ratowników|Возвращение спасателей|Rick zamyka awaryjny portal, ale twoja historia się nie kończy. Z doliny nadchodzi nowy sygnał; Ron zaprasza cię do transportera Aurelii.|Рик закрывает аварийный портал, но твоя история продолжается. Из долины приходит новый сигнал; Рон приглашает тебя в транспорт Аурелии.|Wejdź do transportera|Войти в транспорт
Ludzie z doliny|Люди из долины|Na pokładzie siedzą ocaleni. Dziecko ściska pękniętą zabawkę, a starszy mężczyzna pyta, czy Aurelia przyjmie także tych, którzy nie mają nic.|На борту сидят спасённые. Ребёнок сжимает сломанную игрушку, а старик спрашивает, примет ли Аурелия тех, у кого ничего нет.|Pomóż pasażerom|Помочь пассажирам
Przez chmury|Сквозь облака|Transporter wznosi się ponad zraniony świat. W oddali otwiera się błękitny portal; latarnik przygasa, żeby dzieci mogły zasnąć.|Транспорт поднимается над раненым миром. Вдали раскрывается синий портал; фонарщик приглушает свет, чтобы дети могли уснуть.|Sprawdź pasy bezpieczeństwa|Проверить крепления
Widok Aurelii|Вид Аурелии|Za portalem rozciągają się ogrody i jasne miasta. Ron wskazuje szpital, warsztaty i domy: „To wszystko ma działać dla mieszkańców”.|За порталом раскинулись сады и светлые города. Рон показывает больницу, мастерские и дома: «Всё это должно работать для жителей».|Zapamiętaj drogę|Запомнить дорогу
Lądowisko|Посадочная площадка|Na lądowisku czekają lekarze i tłumacze. Nikt nie zabiera uchodźcom bagażu; każdy może zdecydować, kto pomoże mu wysiąść.|На площадке ждут врачи и переводчики. У беженцев не отбирают вещи; каждый сам выбирает, кто поможет ему выйти.|Wyprowadź dziecko|Помочь ребёнку выйти
Nowe dokumenty|Новые документы|Urzędniczka pyta o imię, lecz nie wymaga wspomnień, których nie masz. Proponuje tymczasowy identyfikator i wyjaśnia, jakie dane zostaną zapisane.|Сотрудница спрашивает имя, но не требует воспоминаний, которых у тебя нет. Она предлагает временный документ и объясняет, какие сведения запишут.|Przyjmij identyfikator|Получить документ
Pokój z oknem|Комната с окном|Dostajesz mały pokój z widokiem na ogród. Na stole leżą czyste ubrania i kartka: pomoc możesz przyjąć, ale nie musisz niczego obiecywać.|Тебе дают небольшую комнату с видом на сад. На столе одежда и записка: помощь можно принять, не обещая ничего взамен.|Odpocznij przy oknie|Отдохнуть у окна
Nocny sygnał|Ночной сигнал|Znak na dłoni rozbłyska mimo zamknięcia Bramy. W świetle pojawia się mapa innego świata i zdanie: „Pierwsza szczelina była próbą”.|Знак на ладони вспыхивает даже после закрытия Врат. В свете возникает карта другого мира и фраза: «Первая трещина была пробой».|Powiadom Rona|Сообщить Рону
Warsztaty o świcie|Мастерские на рассвете|Ron już pracuje. Rick śpi na skrzynce, a mały robot pilnuje, żeby kawa nie wybuchła. Pokazujesz im nocny sygnał.|Рон уже работает. Рик спит на ящике, а маленький робот следит, чтобы кофе не взорвался. Ты показываешь им ночной сигнал.|Pokaż mapę|Показать карту
Toster z pretensjami|Тостер с претензиями|Toster żąda prawa do urlopu i grozi spaleniem śniadania. Ron negocjuje, Rick poprawia zasilanie; możesz pomóc obu, zanim warsztat zacznie dymić.|Тостер требует отпуск и грозит сжечь завтрак. Рон ведёт переговоры, Рик чинит питание; можно помочь, пока мастерская не задымилась.|Odłącz wadliwy kabel|Отключить неисправный кабель
Sygnał bez nadawcy|Сигнал без отправителя|Mapa nie pochodzi z waszej Bramy. Rick odkrywa powtarzający się rytm, podobny do wezwania pomocy ukrytego pod zakłóceniami.|Карта пришла не из ваших Врат. Рик обнаруживает повторяющийся ритм, похожий на сигнал бедствия под помехами.|Zapisz rytm|Записать ритм
Starszy uczeń|Старший ученик|Starszy z braci pomaga Ronowi segregować części. Przyznaje, że boi się kolejnej wyprawy, ale wreszcie znalazł pracę, za którą odpowiada.|Старший из братьев помогает Рону разбирать детали. Он признаётся, что боится новой экспедиции, но наконец нашёл дело, за которое отвечает.|Zapytaj o jego doświadczenie|Расспросить о его опыте
Próba narzędzi|Проверка инструментов|Ron daje ci próbny stabilizator. Jeśli źle ustawisz cewkę, urządzenie zgaśnie; najpierw możesz obejrzeć schemat zamiast zgadywać.|Рон даёт учебный стабилизатор. При неверной установке катушки он погаснет; сначала можно изучить схему вместо догадок.|Przeczytaj schemat|Прочитать схему
Drzwi Ricka|Дверь Рика|Rick otwiera portal wielkości talerza. Po drugiej stronie pada śnieg, chociaż czujnik pokazuje wysoką temperaturę. Dane wymagają sprawdzenia.|Рик открывает портал размером с тарелку. За ним идёт снег, хотя датчик показывает жару. Показания надо проверить.|Wyślij sondę|Отправить зонд
Zapis sondy|Запись зонда|Sonda pokazuje miasto w dwóch chwilach naraz: mieszkańcy chodzą między ruinami swoich przyszłych domów. Granica miesza czas z przestrzenią.|Зонд показывает город сразу в двух временах: жители идут среди руин своих будущих домов. Грань смешивает время и пространство.|Zachowaj nagranie|Сохранить запись
Pierwsza odpowiedź|Первый ответ|Z zakłóceń przebija się dziewczęcy głos. Prosi, żeby nie wysyłać broni: ich maszyny reagują na zagrożenie i pogłębiają szczelinę.|Сквозь помехи слышен голос девушки. Она просит не присылать оружие: их машины реагируют на угрозу и расширяют трещину.|Obiecaj ostrożność|Обещать осторожность
Wezwanie do Rady|Вызов в Совет|Ari prosi o przedstawienie danych Radzie. Nie każe ci udawać eksperta; chce usłyszeć, co widziałeś i czego jeszcze nie wiesz.|Ари просит представить данные Совету. Он не требует изображать эксперта; ему важно, что ты видел и чего пока не знаешь.|Przygotuj raport|Подготовить доклад
Dziesięć miejsc|Десять мест|W sali stoi okrągły stół z dziesięcioma miejscami. Nie ma podwyższonego tronu. Indigo wskazuje wolne krzesło dla świadka obok stołu.|В зале круглый стол с десятью местами. Возвышенного трона нет. Индиго показывает отдельное кресло для свидетеля рядом со столом.|Usiądź jako świadek|Сесть на место свидетеля
Pytanie Ariego|Вопрос Ари|Ari pyta, czy ratowanie jednego świata może zagrozić innemu. Ron przedstawia ryzyko; Rick przyznaje, że bez dodatkowych danych nie potrafi go wykluczyć.|Ари спрашивает, не поставит ли спасение одного мира под угрозу другой. Рон объясняет риск; Рик признаёт, что данных пока недостаточно.|Przyznaj, czego nie wiesz|Признать, чего не знаешь
Głos Indigo|Слово Индиго|Indigo proponuje przygotować bezpieczne schronienie przed wyprawą. Jej moc tworzy przestrzeń dla nowych mieszkańców, ale nie zastąpi ich własnego wyboru.|Индиго предлагает подготовить убежище до экспедиции. Её сила создаст место для новых жителей, но не заменит их собственного выбора.|Wesprzyj plan schronienia|Поддержать план убежища
Wyliczenia Thomasa|Расчёты Томаса|Thomas układa nad stołem świetlne warstwy czasu. Znajduje wąskie okno, w którym portal nie przyspieszy rozpadu obcego miasta.|Томас разворачивает над столом светящиеся слои времени. Он находит короткий промежуток, когда портал не ускорит распад чужого города.|Zapamiętaj godzinę wejścia|Запомнить время перехода
Warunek Severusa|Условие Северуса|Severus żąda zapasu antidotum i procedury odwrotu. „Odwaga bez przygotowania daje mi dodatkowych pacjentów”. Wskazuje ci listę objawów kontaktu z Granicą.|Северус требует запас противоядий и порядок отступления. «Храбрость без подготовки добавляет мне пациентов». Он показывает симптомы воздействия Грани.|Zabierz listę objawów|Взять список симптомов
Ostrzeżenie Weskera|Предупреждение Вескера|Wesker porównuje twoją regenerację z wynikami badań. Znak pomaga goić drobne rany, lecz przeciążenie może uszkodzić układ nerwowy. Nie jesteś niezniszczalny.|Вескер изучает твою регенерацию. Знак заживляет мелкие раны, но перегрузка способна повредить нервную систему. Ты не неуязвим.|Ustal bezpieczny limit|Установить безопасный предел
Priorytet Iary|Приоритет Иары|Iara pyta o dzieci, starszych i rannych po drugiej stronie. Rada wpisuje ich ewakuację do planu jeszcze przed uruchomieniem urządzeń.|Иара спрашивает о детях, стариках и раненых за порталом. Совет включает их эвакуацию в план ещё до запуска устройств.|Przyjmij rolę łącznika|Стать связным
Plan Rona|План Рона|Ron przygotowuje trzy stabilizatory zamiast jednego wielkiego. Awaria pojedynczego urządzenia nie powinna pozbawić całej wyprawy drogi powrotnej.|Рон готовит три стабилизатора вместо одного большого. Поломка одного не должна лишить всю экспедицию пути назад.|Sprawdź urządzenia|Проверить устройства
Zakład Ricka|Пари Рика|Rick zakłada się ze Starszym, że portal ruszy bez kopnięcia. Urządzenie nie odpowiada. „To nie kopnięcie. Kalibracja butem”. Wreszcie świeci stabilnie.|Рик спорит со Старшим, что портал заработает без пинка. Устройство молчит. «Это не пинок. Калибровка ботинком». Наконец оно светится ровно.|Zweryfikuj stabilność|Проверить устойчивость
Patrol Homelendera|Патруль Хоумлендера|Homelander ma osłaniać transporty, nie atakować miasto. Ćwiczy z ratownikami przenoszenie rannych tak, żeby nie pogłębić ich obrażeń.|Хоумлендер будет прикрывать транспорты, а не атаковать город. Он тренируется с медиками переносить раненых, не усугубляя травмы.|Sprawdź trasę ratunkową|Проверить маршрут спасения
Granica Eliasa|Рубеж Элиаса|Elias wyznacza miejsce, poza którym nikt nie pozostaje samotnie. „Wrócisz z meldunkiem, nie z legendą o własnej śmierci”.|Элиас отмечает рубеж, за которым нельзя оставаться одному. «Вернёшься с докладом, а не с легендой о собственной смерти».|Zapamiętaj punkt zbiórki|Запомнить место сбора
Decyzja Rady|Решение Совета|Rada zatwierdza rozpoznanie i pomoc mieszkańcom. Ari podkreśla, że wyprawa nie daje Aurelii prawa do przejęcia obcego świata.|Совет утверждает разведку и помощь жителям. Ари подчёркивает: экспедиция не даёт Аурелии права присвоить чужой мир.|Potwierdź cel misji|Подтвердить цель миссии
Przygotowanie ekwipunku|Подготовка снаряжения|Przed portalem otrzymujesz zestaw pierwszej pomocy i komunikator. Możesz sprawdzić ich działanie albo przejść wcześniej, by pomóc ustawić stanowisko.|Перед порталом тебе дают аптечку и связь. Можно проверить оборудование или пройти раньше, чтобы помочь развернуть пост.|Sprawdź komunikator|Проверить связь
Krok przez portal|Шаг через портал|Przechodzisz przez chłodne światło. Po drugiej stronie deszcz zatrzymuje się na chwilę w powietrzu, a potem spada naraz na bruk.|Ты проходишь сквозь холодный свет. На другой стороне дождь замирает в воздухе, а затем разом падает на мостовую.|Rozejrzyj się spokojnie|Спокойно осмотреться
Miasto dwóch cieni|Город двух теней|Każdy człowiek rzuca dwa cienie w różnych kierunkach. Rick ostrzega, że jeden pokazuje ruch z przyszłości; nie zawsze zdąży się spełnić.|Каждый человек отбрасывает две тени в разные стороны. Рик предупреждает: одна показывает движение из будущего, которое ещё может не случиться.|Obserwuj cienie|Наблюдать за тенями
Spotkanie z Lirą|Встреча с Лирой|Dziewczyna z transmisji przedstawia się jako Lira. Prowadzi was do schronienia i prosi, żebyście nie dotykali czerwonych znaków na ścianach.|Девушка из передачи называет себя Лирой. Она ведёт вас в убежище и просит не трогать красные знаки на стенах.|Zaufaj przewodniczce|Довериться проводнице
Schron pod placem|Убежище под площадью|Pod placem czekają mieszkańcy. Niektórzy boją się obcych ratowników bardziej niż szczeliny. Lira pozwala im obejrzeć wasze urządzenia z daleka.|Под площадью ждут жители. Некоторые боятся чужих спасателей сильнее трещины. Лира предлагает осмотреть ваши приборы с безопасного расстояния.|Wyjaśnij działanie sprzętu|Объяснить работу приборов
Dziecko i dwa jutra|Ребёнок и два завтра|Chłopiec pokazuje dwa rysunki tego samego domu: na jednym jest ogród, na drugim popiół. Pyta, który stanie się prawdziwy.|Мальчик показывает два рисунка одного дома: на первом сад, на втором пепел. Он спрашивает, какой станет настоящим.|Powiedz prawdę bez obietnic|Ответить честно
Czerwony znak|Красный знак|Znak na ścianie pulsuje, gdy podnosisz komunikator. To czujnik dawnego systemu obronnego; może uznać silny sygnał za początek ataku.|Знак на стене пульсирует, когда ты поднимаешь передатчик. Это датчик старой обороны; сильный сигнал он может принять за начало атаки.|Zmniejsz moc nadajnika|Уменьшить мощность связи
Puste targowisko|Пустой рынок|Na rynku leżą niedokończone zakupy. Przez szczelinę w straganie widzisz ten sam plac pełen ludzi. Ron zabrania przechodzić bez pomiaru.|На рынке лежат брошенные покупки. Через трещину в прилавке видна эта же площадь с людьми. Рон запрещает переход без измерений.|Oznacz szczelinę|Отметить трещину
Zegar na wieży|Часы на башне|Wskazówki cofają się za każdym razem, gdy bije dzwon. Thomas przez łączność prosi o zapis całego cyklu, nie tylko jednej chwili.|Стрелки отступают при каждом ударе колокола. Томас просит записать полный цикл, а не один момент.|Nagraj cykl zegara|Записать цикл часов
Droga do archiwum|Дорога в архив|Lira zna przejście między dwoma bezpiecznymi budynkami. Krótsza droga prowadzi przez odsłonięty plac; wybór może kosztować siły lub czas.|Лира знает проход между безопасными зданиями. Короткий путь лежит через открытую площадь; выбор обойдётся силами или временем.|Idź osłoniętą drogą|Идти защищённым путём
Zamknięty katalog|Закрытый каталог|Archiwista nie chce oddać danych obcym. Proponujesz skopiować tylko zapisy awarii w jego obecności. Lira potwierdza, że reszta zostanie na miejscu.|Архивист не хочет отдавать данные чужакам. Ты предлагаешь скопировать только записи аварии при нём. Лира подтверждает: остальное останется здесь.|Poproś o ograniczony dostęp|Попросить ограниченный доступ
Plan dawnej maszyny|План древней машины|Zapisy pokazują urządzenie budowane jako ochrona miasta. Ktoś odłączył ogranicznik, próbując pobierać energię z Granicy bez końca.|Записи показывают машину, созданную для защиты города. Кто-то отключил ограничитель, пытаясь бесконечно получать энергию из Грани.|Skopiuj plan ogranicznika|Скопировать план ограничителя
Brakująca strona|Пропавшая страница|Z instrukcji wyrwano jedną stronę. Na brzegu pozostał odcisk rękawicy i numer warsztatu. Rick zauważa, że tusz wciąż jest świeży.|Из инструкции вырвана страница. На краю остался след перчатки и номер мастерской. Рик замечает, что чернила ещё свежие.|Zapisz numer warsztatu|Записать номер мастерской
Pracownia pod schodami|Мастерская под лестницей|W pracowni ukrywa się mechanik. Przyznaje, że zmienił ustawienia na rozkaz przełożonego, ale bał się powiedzieć mieszkańcom prawdę.|В мастерской прячется механик. Он признаётся, что изменил настройки по приказу начальника, но боялся рассказать жителям правду.|Wysłuchaj mechanika|Выслушать механика
Strona z ostrzeżeniem|Страница с предупреждением|Mechanik oddaje brakującą stronę. Ogranicznik wymaga trzech kotew i zgody lokalnego operatora; wymuszenie dostępu uruchomi obronę miasta.|Механик отдаёт страницу. Ограничителю нужны три якоря и согласие местного оператора; взлом включит городскую оборону.|Zabierz ostrzeżenie|Взять предупреждение
Ranny strażnik|Раненый страж|Przy wyjściu leży strażnik, którego ciało migocze między dwiema chwilami. Iara prosi, żeby nie ciągnąć go przez portal bez zabezpieczenia.|У выхода лежит страж, чьё тело мерцает между двумя временами. Иара просит не переносить его через портал без защиты.|Ustabilizuj nosze|Закрепить носилки
Przyjazd medyków|Прибытие медиков|Severus ustawia wokół noszy krąg, a Wesker kontroluje regenerację tkanek. Strażnik odzyskuje przytomność i wskazuje wejście do sterowni.|Северус ставит вокруг носилок защитный круг, Вескер следит за регенерацией тканей. Страж приходит в себя и указывает вход в центр управления.|Zapamiętaj wejście|Запомнить вход
Trzy kotwy|Три якоря|Ron rozkłada plan miasta. Pierwsza kotwa trafi do wieży, druga do kanałów, trzecia pod główną maszynę. Muszą działać wspólnie.|Рон разворачивает план города. Первый якорь поставят в башне, второй в каналах, третий под главной машиной. Они должны работать вместе.|Wybierz pierwsze stanowisko|Выбрать первый пост
Kotwa na wieży|Якорь на башне|Na schodach wieży brakuje kilku stopni. Starszy niesie urządzenie; możesz asekurować go liną albo najpierw sprawdzić podest sondą.|В башне не хватает ступеней. Старший несёт прибор; можно страховать его тросом или сначала проверить площадку зондом.|Sprawdź podest sondą|Проверить площадку зондом
Chwiejny podest|Шаткая площадка|Podest przesuwa się o kilka sekund wstecz. Homelander przytrzymuje urządzenie, ale potrzebuje od ciebie sygnału w stabilnym momencie cyklu.|Площадка сдвигается на несколько секунд назад. Хоумлендер держит устройство, но ему нужен твой сигнал в устойчивый момент цикла.|Odlicz właściwy moment|Отсчитать нужный момент
Pierwsze światło|Первый свет|Kotwa rozbłyska i jedna z podwójnych ulic wraca na swoje miejsce. Mieszkańcy widzą pierwszy rezultat; Lira prosi o powtórzenie instrukcji dla drugiego zespołu.|Якорь вспыхивает, и одна раздвоенная улица возвращается на место. Жители видят результат; Лира просит повторить инструкцию второй группе.|Przekaż instrukcję|Передать инструкцию
Wejście do kanałów|Вход в каналы|Pod miastem słychać ten sam rytm co w sygnale pomocy. Woda niesie kawałki przedmiotów z innych światów. Latarnik bada bezpieczną głębokość.|Под городом слышен ритм сигнала бедствия. Вода несёт обломки из других миров. Фонарщик измеряет безопасную глубину.|Poczekaj na pomiar|Дождаться измерения
Zalany korytarz|Затопленный коридор|Druga kotwa jest cięższa, niż wyglądała na stole. Ron proponuje przenieść ją na konstrukcie; mechanik zna suchą, lecz dłuższą drogę.|Второй якорь тяжелее, чем казался на столе. Рон предлагает перевозку на конструкте; механик знает сухой, но длинный путь.|Skorzystaj z konstruktu|Воспользоваться конструктом
Cień w wodzie|Тень в воде|W wodzie pojawia się twoja twarz sprzed przebudzenia. Obraz powtarza pytanie o imię. Wesker przypomina przez łączność, żeby nie odpowiadać impulsowi.|В воде появляется твоё лицо до пробуждения. Образ спрашивает имя. Вескер по связи напоминает не отвечать чужому импульсу.|Skup się na zadaniu|Сосредоточиться на задании
Drugi stabilizator|Второй стабилизатор|Ron prowadzi cię przez podłączenie urządzenia. Jego głos urywa się, gdy zakłócenia rosną. Zostaje zapisany schemat i twoja własna decyzja.|Рон помогает подключить устройство. Связь обрывается при усилении помех. Остаются сохранённая схема и твоё решение.|Wykonaj zapisany schemat|Следовать сохранённой схеме
Przeciążona cewka|Перегруженная катушка|Cewka zaczyna czerwienieć. Możesz bezpiecznie wyłączyć urządzenie i stracić chwilę albo schłodzić je ręcznie kosztem własnych sił.|Катушка краснеет. Можно безопасно отключить прибор, потеряв время, или охлаждать вручную, расходуя силы.|Wyłącz i popraw chłodzenie|Отключить и исправить охлаждение
Druga kotwa działa|Второй якорь работает|Urządzenie odzyskuje równowagę. Woda wraca do normalnego nurtu; znikają odłamki obcych światów. W oddali jednak odzywa się alarm sterowni.|Устройство стабилизируется. Вода течёт нормально; обломки чужих миров исчезают. Но вдали звучит тревога центра управления.|Zgłoś uruchomienie|Сообщить о запуске
Miasto reaguje|Ответ города|System obronny rozpoznaje zmianę energii. Nad ulicami budzą się strażnicze golemy. Lira prosi, żebyście nie odpowiadali atakiem.|Оборона замечает изменение энергии. Над улицами просыпаются сторожевые големы. Лира просит не отвечать нападением.|Schowaj aktywny nadajnik|Убрать активный передатчик
Przejście bez walki|Проход без боя|Elias odgradza golemy osłoną, dając cywilom czas na odejście. Możesz wskazać im bezpieczną trasę albo zostać przy urządzeniach.|Элиас удерживает големов щитом, давая людям уйти. Можно показать безопасный маршрут или остаться у приборов.|Poprowadź mieszkańców|Провести жителей
Operator maszyny|Оператор машины|W sterowni czeka przełożony mechanika. Twierdzi, że bez pobierania energii miasto upadnie. Thomas pokazuje mu skutki obecnego przeciążenia.|В центре ждёт начальник механика. Он считает, что без добычи энергии город погибнет. Томас показывает последствия нынешней перегрузки.|Pokaż pomiary Thomasa|Показать расчёты Томаса
Zgoda zamiast rozkazu|Согласие вместо приказа|Ari łączy się ze sterownią i proponuje pomoc w odbudowie zasilania. Operator może zgodzić się na wyłączenie, zachowując odpowiedzialność za własne miasto.|Ари предлагает помощь с восстановлением питания. Оператор может согласиться на отключение, сохранив ответственность за свой город.|Poproś o dobrowolną zgodę|Попросить добровольное согласие
Trzecia kotwa|Третий якорь|Operator otwiera dolny poziom. Pod maszyną pulsuje ogromny pierścień. Rick ostrzega, że ostatnia kotwa musi wejść w sam środek jego cyklu.|Оператор открывает нижний уровень. Под машиной пульсирует огромный круг. Рик предупреждает: последний якорь должен попасть точно в середину цикла.|Porównaj rytm z nagraniem|Сравнить ритм с записью
Ręce Starszego|Руки Старшего|Starszy zgłasza się do montażu, choć palce mu drżą. Ron daje mu prostą, ważną pracę; resztę bierze na siebie. Nikt nie musi udowadniać odwagi samotnie.|Старший вызывается монтировать, хотя руки дрожат. Рон поручает ему простую важную работу, остальное берёт на себя. Смелость не надо доказывать в одиночку.|Asekuruj montaż|Страховать монтаж
Pęknięcie pod stopami|Трещина под ногами|Podest rozpada się w dwóch miejscach. Możesz pomóc Starszemu utrzymać kotwę albo przenieść kabel na stabilną podporę; oba zadania są potrzebne.|Площадка трескается в двух местах. Можно помочь Старшему удержать якорь или перенести кабель на устойчивую опору; нужны оба действия.|Podeprzyj kabel|Закрепить кабель
Znak odpowiada|Знак отвечает|Twój znak zaczyna świecić w rytmie pierścienia. Nie wymaga dotknięcia maszyny: opaska Weskera może przekazać sygnał bez niebezpiecznego kontaktu.|Твой знак светится в ритме кольца. Касаться машины не обязательно: браслет Вескера передаст сигнал без опасного контакта.|Przekaż sygnał ostrożnie|Осторожно передать сигнал
Trzy światła naraz|Три огня одновременно|Wszystkie kotwy zapalają się jednocześnie. Podwójne cienie znikają. Ron krzyczy, żeby niczego nie odłączać przed potwierdzeniem pomiarów.|Все якоря вспыхивают одновременно. Двойные тени исчезают. Рон кричит не отключать ничего до подтверждения измерений.|Sprawdź odczyty|Проверить показания
Fałszywa cisza|Ложная тишина|Alarmy milkną, lecz Rick dostrzega ruch za powierzchnią szczeliny. Ktoś po drugiej stronie próbował wykorzystać miejską maszynę jako przejście.|Сигналы стихли, но Рик замечает движение за трещиной. Кто-то пытался превратить городскую машину в проход.|Zapisz obcy sygnał|Записать чужой сигнал
Ostatnia fala|Последняя волна|Granica uderza w osłony Thomasa. Indigo podtrzymuje przestrzeń schronienia, a Homelander wywozi ostatnich rannych. Twoim zadaniem pozostaje utrzymać łączność.|Грань бьёт по щитам Томаса. Индиго удерживает убежище, Хоумлендер вывозит последних раненых. Твоя задача — сохранить связь.|Utrzymaj kanał ratunkowy|Удержать канал спасателей
Ogranicznik wraca|Возвращение ограничителя|Operator i Ron przywracają dawny ogranicznik. Maszyna przestaje pobierać obcą energię; miasto pogrąża się w ciemności, ale już nie rozpada się w czasie.|Оператор и Рон возвращают ограничитель. Машина прекращает забирать чужую энергию; город темнеет, но больше не распадается во времени.|Potwierdź stabilność miasta|Подтвердить устойчивость города
Prąd dla szpitala|Энергия для больницы|Przenośne źródła z Aurelii wystarczą najpierw tylko na szpital i schronienie. Iara pyta mieszkańców o pozostałe pilne potrzeby.|Переносной энергии Аурелии пока хватает лишь больнице и убежищу. Иара спрашивает жителей о других срочных нуждах.|Sporządź listę potrzeb|Составить список нужд
Miasto wybiera|Выбор города|Mieszkańcy sami wyznaczają zespoły odbudowy. Lira prosi cię o opis urządzeń, aby pomoc z Aurelii nie zostawiła ich zależnych od obcych.|Жители сами назначают группы восстановления. Лира просит описание приборов, чтобы помощь Аурелии не сделала город зависимым от чужаков.|Przekaż instrukcje mieszkańcom|Передать инструкции жителям
Pożegnanie Liry|Прощание с Лирой|Lira zostaje odbudowywać miasto. Daje ci szkic dwóch cieni, już przekreślonych. „Przyjedź kiedyś, gdy nie będzie trzeba nikogo ratować”.|Лира остаётся восстанавливать город. Она дарит рисунок двух перечёркнутых теней. «Приезжай когда-нибудь, когда никого не нужно спасать».|Przyjmij rysunek|Принять рисунок
Powrót do domu Rady|Возвращение в дом Совета|Portal prowadzi do Aurelii. Na dziedzińcu czekają rodziny ratowników, nie wojskowa parada. Starszy pierwszy raz wraca z misji, za którą sam odpowiadał.|Портал ведёт в Аурелию. Во дворе ждут семьи спасателей, а не военный парад. Старший впервые возвращается с задания, за которое отвечал сам.|Przywitaj czekających|Поздороваться с ожидающими
Raport bez legend|Доклад без легенд|Ari prosi o zapis błędów równie dokładny jak sukcesów. Możesz opowiedzieć o swoich wątpliwościach; żadna z nich nie unieważni wykonanej pracy.|Ари просит записать ошибки так же точно, как успехи. Можно рассказать о сомнениях; они не перечёркивают сделанную работу.|Opisz również błędy|Описать и ошибки
Świat, który ocalał|Мир, который уцелел|Na ekranie widać pierwsze światła w odbudowywanym mieście. Rada zatwierdza dalszą pomoc, a mieszkańcy Aurelii zgłaszają się do wymiany wiedzy.|На экране первые огни восстанавливаемого города. Совет продолжает помощь, а жители Аурелии предлагают обмен знаниями.|Dołącz do zespołu pomocy|Присоединиться к помощи
Wieczór w warsztacie|Вечер в мастерской|Rick, Ron i Starszy rozkładają kolację między narzędziami. Toster ogłasza zwycięstwo związku zawodowego. Ron obiecuje mu wolną niedzielę.|Рик, Рон и Старший ужинают среди инструментов. Тостер объявляет победу профсоюза. Рон обещает ему выходной в воскресенье.|Usiądź z przyjaciółmi|Сесть с друзьями
Twój własny pokój|Твоя комната|Wracasz do pokoju z widokiem na ogród. Nie pamiętasz jeszcze całego dawnego życia, ale znasz już imiona ludzi, którym możesz zaufać.|Ты возвращаешься в комнату с видом на сад. Прежнюю жизнь помнишь не полностью, но уже знаешь имена тех, кому доверяешь.|Zapisz wspomnienia|Записать воспоминания
Co kryje zapis|Что скрывает запись|W obcym sygnale znajdujesz współrzędne wykraczające poza uratowany świat. Wesker odkrywa, że znak na dłoni reaguje na nie także podczas snu.|В чужом сигнале обнаруживаются координаты за пределами спасённого мира. Вескер выясняет: знак реагирует на них даже во сне.|Przekaż zapis Weskerowi|Передать запись Вескеру
Nieznana pieczęć|Неизвестная печать|Thomas rozpoznaje budowę pieczęci, lecz nie jej twórcę. Nie chce zgadywać. Prosi Esserata o porównanie symbolu z archiwami dawnych cywilizacji.|Томас понимает устройство печати, но не знает создателя. Он не гадает, а просит Эссерата сверить символ с архивами древних цивилизаций.|Pomóż porównać symbole|Помочь сравнить символы
Sygnał z pustki|Сигнал из пустоты|W nocy komunikator odbiera jedno zdanie: „Widzieliśmy, co zrobiliście”. Nie wiadomo, czy to podziękowanie, ostrzeżenie czy początek rozmowy.|Ночью передатчик принимает фразу: «Мы видели, что вы сделали». Неясно, благодарность это, предупреждение или начало разговора.|Zachowaj wiadomość|Сохранить сообщение
Przed następną wyprawą|Перед следующей экспедицией|Ari zwołuje Radę na ranek. Rick sprawdza portal, Ron przygotowuje pustą skrzynkę na nowe narzędzia. Tym razem czekają również na twoją decyzję.|Ари созывает Совет на утро. Рик проверяет портал, Рон готовит пустой ящик для новых инструментов. Теперь они ждут и твоего решения.|Zgłoś gotowość|Сообщить о готовности
Rozdział pierwszy: nowy próg|Глава первая: новый порог|Za oknem wschodzi słońce Aurelii. Na stole leży mapa świata, którego nikt jeszcze nie odwiedził. Pierwszy rozdział zostaje zapisany. Aktualizacja wkrótce.|За окном восходит солнце Аурелии. На столе карта мира, в котором ещё никто не был. Первая глава сохранена. Обновление скоро.|Czekaj na dalszy ciąg|Ждать продолжения
`.trim().split('\n').map(line=>line.split('|'));
const ru={
wake:['Пробуждение у Грани','Ты просыпаешься на влажном мху без воспоминаний. Над тобой прозрачный лис, каменный великан и существо с глазами-фонарями. На броне знак Аурелии. За деревьями Грань поглощает горизонт.',['Спросить, где ты','Вскочить и убежать','Притвориться спящим']],
names:['Имя без воспоминаний','«Это Пограничье Аурелии. Я разведывательный дрон. Лис — голографический проводник, великан — спасательный конструкт Рона». Лис касается ладони; появляется знак расколотого круга.',['Показать знак всем','Спрятать ладонь и осмотреться']],
run:['Лес возвращает назад','Любая тропа приводит на ту же поляну. Прозрачный лис ждёт у корня с твоей потерянной сумкой в пасти.',['Принять сумку и вернуться','Залезть на дерево']],
listen:['Разговор над спящим','«Не рассказывай о Вратах. Он должен решить сам», — говорит великан. «Сначала пусть узнает цену», — отвечает фонарщик. Под рукой лежит сумка.',['Открыть глаза и спросить о цене','Потянуться к сумке']],
mark:['Расколотый круг','Знак открывает доступ к Вратам. Когда-то они разделяли миры, теперь засасывают людей и воспоминания. Можно восстановить их или пройти домой, но сначала надо добраться.',['Обещать помощь','Сказать, что ищешь путь домой']],
clearing:['На краю поляны','На востоке дым поселения, на севере башня. В сумке маленький нож, пустая фляга и сложенный лист.',['Развернуть лист','Наполнить флягу у источника']],
bag:['Уцелевшие вещи','В сумке нож, пустая фляга и карта. На обороте твоим почерком написано: «Не доверяй голосу, который знает твоё имя».',['Прочитать карту','Сначала найти воду']],
tree:['Над кронами','С дерева видна чёрная трещина в небе, башня и поселение. Ветка ломается. Великан ловит тебя перед ударом о землю.',['Поблагодарить и принять помощь','Спросить, зачем он тебя спасает']],
map:['Три дороги','На карте поселение, мост и архив в башне. У Врат два гнезда: для света и памяти. Лис указывает на поселение, великан — на башню.',['Идти в поселение','Идти к башне','Сначала найти воду']],
spring:['Отражение в воде','Отражение шевелит губами без тебя: «Возвращайся домой. Оставь их». Лис рычит на воду. Сама вода чистая.',['Наполнить флягу и идти в поселение','Отвернуться от голоса и идти к башне']],
village:['Поселение под стеклом','У жителей деревянные лица и стеклянные руки. Ребёнок вытаскивает друга из-под перевёрнутой повозки. Торговец обещает объяснить устройство Врат.',['Помочь ребёнку','Подойти к торговцу','Найти место для отдыха']],
rescue:['Маленький механик','Вы с великаном поднимаете повозку. Спасённый дарит латунную шестерню. Ребёнок рассказывает о туннеле под мостом, которого нет на карте.',['Запомнить туннель','Попросить воду и отдохнуть']],
merchant:['Цена света','Торговец меняет кристалл на нож. Фонарщик узнаёт кристалл: его украли из общего фонаря поселения.',['Обменять нож на кристалл','Потребовать вернуть кристалл жителям','Искать ответ в башне']],
lantern:['Чей это свет?','Торговец отказывается. Великан собирает жителей, ребёнок узнаёт знак на кристалле. Торговец кладёт его на стол до начала ссоры.',['Попросить кристалл взаймы','Оставить кристалл в фонаре и идти к башне']],
rest:['Час тишины','Пожилая жительница даёт хлеб. За окном исчезает часть холма. «Вечно отдыхать нельзя», — говорит лис. Короткий сон возвращает силы.',['Вернуться к торговцу','Отправиться к башне']],
tower:['Башня без дверей','Вход заложен изнутри. Надпись на статуе: «Я открываюсь тому, кто признаёт своё незнание». Рядом узкий лаз.',['Сказать: я не знаю, кто я','Проползти в лаз','Вернуться в поселение']],
archive:['Архив пропавших','В банках на полках хранятся воспоминания. В одной видишь себя строителем Врат. Хранитель Эссерат спрашивает: «Хочешь правду или инструменты?»',['Вернуть воспоминание','Узнать, как починить Врата','Спросить об источнике света']],
memory:['Твоё давнее решение','Ты вспоминаешь: Врата должны соединять миры, не покорять их. Кто-то убрал защиту и скрыл твою память. Два регулятора надо включить одновременно.',['Взять воспоминание и инструкцию','Найти свет для второго гнезда']],
manual:['Равновесие вместо силы','Кристалл или призма дают энергию. Память либо инструкция возвращают управление. Без обоих компонентов трещину можно только закрыть. Для восстановления потребуется помощь.',['Взять призму в мастерской','Идти на мост']],
prism:['Последняя призма','Эссерат отдаст источник света за полную флягу. Можно также аккуратно разобрать запасную лампу.',['Обменять воду на призму','Разобрать запасную лампу','Идти без призмы']],
bridge:['Мост над пустотой','У реки нет дна. На мосту страж, который помнит каждую ложь. Вдалеке знакомый голос обещает: «Ты почти дома».',['Поговорить со стражем','Пройти туннелем','Пробежать по мосту']],
guardian:['Вопрос стража','«Кого возьмёшь, если Врата пропустят только одного?» Страж смотрит на спутников. Фонарщик дрожит, лис ждёт ответа.',['Признать, что ещё не знаешь','Сказать, что сначала спасёшь себя','Обещать никого не оставить']],
tunnel:['Под каменным мостом','Шестерня открывает потайную калитку. В туннеле обнаруживаешь рабочий провод к Вратам. Фонарщик отмечает его путь на карте.',['Сохранить схему и выйти за мостом']],
fall:['Сломанная доска','Доска исчезает под ногами. Великан ловит тебя за сумку, лис помогает подняться. Ты теряешь силы, но возвращаешься на безопасный берег.',['Попросить короткий отдых','Выпить воду']],
cross:['За последним берегом','В долине исчезают цвета. Голос знает твоё имя, но берёт слова из твоей памяти. Великан предлагает идти вместе.',['Идти со спутниками','Пойти одному','Исследовать провода']],
camp:['Огонь на краю мира','У костра спутники рассказывают об утратах. Лис потерял лес, великан — город, фонарщик — звезду. Теперь они говорят с тобой как с другом.',['Рассказать о страхе','Отдохнуть перед дорогой']],
whisper:['Знакомый голос','«Ты не один из них. Возвращайся». В трещине твоя комната, но часы идут назад, за окном пустота.',['Отвергнуть образ и вернуться','Подойти и проверить иллюзию']],
workshop:['Рик и Рон','Портал раскрывается с треском. Рик достаёт дымящийся прибор, Рон — инструменты. Для стабилизатора нужен тот, чей знак распознают Врата.',['Помочь Рону собрать стабилизатор','Спросить Рика, можно ли спасти всех']],
engineers:['Невозможное оставь нам','«Грань не победить ударом. Надо восстановить равновесие», — объясняет Рон. Рик вызывает Совет Аурелии: нужна помощь.',['Идти в полевой госпиталь','Спросить о плане эвакуации']],
healers:['Иара и Северус','Иара возвращает дыхание беженцу, Северус готовит эликсиры. «Не будешь спасать мир, едва стоя», — говорит он. Иара просит проверить жителей.',['Принять эликсир и проверить поселение','Принять эликсир и заняться Вратами']],
wesker:['Альберт Вескер','Вескер изучает знак. «Это интерфейс, не приговор. Ты решишь сам». Он предлагает защитный браслет и объясняет опасности Грани.',['Надеть браслет','Узнать, что скрывает голос']],
guardians:['Золотой Страж и Архонт','Хоумлендер выносит жителей из долины, Элиас прикрывает последний транспорт. «Путь в Аурелию открыт. Не сможешь восстановить Врата — закрой. Мы спасём людей».',['Показать оставшихся беженцев','Идти в командный пункт']],
mages:['Томас и структура мира','Томас удерживает щит над долиной и отмечает устойчивые участки. «Рику нужен путь для портала, Рону — время для машины. Я дам вам оба».',['Записать указания Томаса','Попросить защиту обратного пути']],
council:['Ари и Индиго','На экране Ари и Индиго. «Аурелия создана для свободной и безопасной жизни граждан. Совет служит им», — говорит Ари. «Спасай мир, а если не можешь — людей», — добавляет Индиго.',['Вернуться к стабилизатору с Риком и Роном','Подтвердить эвакуацию']],
machine:['Сердце Врат','У прибора Рика и Рона два пустых гнезда. Грань давит на щиты Аурелии. Третий регулятор вырван; лис показывает место для света.',['Починить регулятор шестернёй','Сделать обход через провод','Перейти к главной панели']],
controls:['Два гнезда','Знак будит панель. Можно восстановить соединение, перекрыть трещину или проверить путь домой. Решение изменит судьбу долины.',['Вставить свет и готовить ремонт','Найти способ закрыть трещину','Проверить дорогу домой']],
repair:['Вторая ладонь','Управление восстановлено, но два регулятора надо держать вместе. Попроси спутников или используй починенный механизм. Трещина дрожит.',['Доверить второй регулятор друзьям','Запустить починенный регулятор','Закрыть трещину']],
seal:['Цена закрытия','Закрытие остановит поглощение мира, но лишит краткого пути домой. Можно отключить питание ножом либо использовать знак.',['Перерезать провод ножом','Использовать знак','Ещё раз проверить панель']],
home:['Порог возвращения','За трещиной комната детства. Часы идут правильно, но долина останется с открытыми Вратами. Лис не пытается удержать тебя.',['Проверить переход домой','Остаться у панели']],
endingTogether:['Совместная работа','Рик открывает спасательный портал, Рон стабилизирует Грань. Спутники удерживают регуляторы. Это лишь первый успех: вас уже вызывает Аурелия.',['Продолжить с командой']],
endingEngineer:['Работающий мост','Механизм держит регуляторы. Ты записываешь инструкцию, чтобы следующие спасатели не начинали с нуля. Транспорт Аурелии ждёт.',['Продолжить с командой']],
endingSeal:['Спасённая долина','Трещина погасла, жители спасены. Рик готовит отдельный обратный портал. Закрытая старая дорога не означает конца путешествия.',['Продолжить с командой']],
endingStay:['Имя ещё впереди','Знак гаснет, но не исчезает. Индиго помогает жителям. Ты решаешь остаться с командой; своё имя ещё предстоит вспомнить.',['Продолжить с командой']],
endingHome:['Возвращение не состоялось','За порталом знакомая комната, но обследование Рика обнаруживает петлю памяти. Он закрывает опасный проход и предлагает безопасный путь в Аурелию.',['Продолжить с командой']]
};
const data={rows,ru};
if(typeof module==='object'&&module.exports)module.exports=data;else root.ImperiumChapter=data;
})(typeof window==='object'?window:globalThis);
